---
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: install and configure the web
  hosts: webservers
  become: root
  remote_user: root

  roles:
    - web
    - db

