---
# - name: apply common configuration to all nodes
#   hosts: all
#   remote_user: root
#   roles:
#     - common
#
# - name: install and configure the web
#   hosts: webservers
#   become: root
#   remote_user: root
#   roles:
#     - web

- name: install the db
  hosts: webservers
  become: root
  remote_user: root
  roles:
    - db

# - name: install and configure the wordpress
#   hosts: webservers
#   become: root
#   remote_user: root
#   roles:
#     - wordpress
